version: '3.7'

# volumes:
#   dbserver_data: {}

networks:
  kong-net:
    external: false
  
services:

  db_server:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD", "pg_isready -U kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - kong-net
    # volumes:
    #   - dbserver_data:/var/lib/postgresql/data

secrets:
  postgres_password:
    file: ./POSTGRES_PASSWORD